id: hubdrive
version: "1.2"
hosts: [hubdrive.tips, hubdrive.me, hubdrive.sbs, hubdrive.pics]
allowed_hosts: [hubdrive.tips, hubdrive.me, hubdrive.sbs, hubdrive.pics, hubcloud.ist, hubcloud.cx, hubcloud.bz, hubcloud.foo, hubcloud.one, hubcloud.in, hubcloud.ink, hubcloud.fyi]
mode: links
link_selectors:
  - 'a[href*="hubcloud."]'
